### ISSUE TITLE
Better interpolation

### ISSUE THREAD

**Issue by jangernert** [baedert/gtkimageview#3]
The interpolation of scaled down images especially with text can be quite bad. A decent but still fast interpolation method would be appreciated.

The same image in the gimp viewport for reference:
![gimp-viewport](https://cloud.githubusercontent.com/assets/12012494/13415683/04f753d2-df5d-11e5-9c6c-2900027c024e.png)

And now in a gtk imageview:
![gtk-imageview](https://cloud.githubusercontent.com/assets/12012494/13415684/04f94908-df5d-11e5-971f-267a2117dce3.png)

In both cases the image is scaled to 80%

**Comment by baedert** [comment]
That's the point of the currently ongoing work on GtkImageView. The current version is public so you can copy it into your project tree and just change things like that (the cairo fiilter gets set in gtk_image_view_draw)

**Comment by jangernert** [comment]
thx for the tip :)
