### ISSUE TITLE
Zoom Modes

### ISSUE THREAD

**Issue by jangernert** [baedert/gtkimageview#4]
The wiki page of GtkImageView is talking about "zoom modes":

> There are currently 3 zoom modes:
> -GTK_IMAGE_VIEW_ZOOM_MODE_FIT: The minimum size of the widget is 1×1, the natural size the image's size. if the widget's allocation is smaller than the image's size, the image gets scalled to the allocation (i.e. we never scale it up).
> -GTK_IMAGE_VIEW_ZOOM_MODE_ORIGINAL: Minimum size of the widget is the image's size. The image doesn't get scaled.
> -GTK_IMAGE_VIEW_ZOOM_MODE_NONE: See question at the end 

I can't find anything like this in the code. Was this scratched or is it still planed?

**Comment by baedert** [comment]
The zoom modes turned out to just boil down to ft-allocation=TRUE or FALSE anyway, so they don't exist anymore. so _FIT is fit-allocation=TRUE, _ORIGINAL is fit-allocation=FALSE and scale=1.
